# Generated by Django 4.2.6 on 2023-10-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0002_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='Capacity',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='Equipment_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='Hardware_Type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='MAX_POWER',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='OEM',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='Remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='Supported_Cards',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='Techninal_Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='Technology_Supported',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
