# Generated by Django 4.2.6 on 2023-10-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_file_upload_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='file',
        ),
    ]
