# Generated by Django 4.2.6 on 2023-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0004_remove_file_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(max_length=500, null=True)),
                ('Hardware_Type', models.CharField(max_length=500, null=True)),
                ('Equipment_description', models.CharField(max_length=500, null=True)),
                ('Supported_Cards', models.CharField(max_length=500, null=True)),
                ('Technology_Supported', models.CharField(max_length=500, null=True)),
                ('Techninal_Description', models.CharField(max_length=500, null=True)),
                ('Capacity', models.CharField(max_length=500, null=True)),
                ('MAX_POWER', models.CharField(max_length=500, null=True)),
                ('Remarks', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='Capacity',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='Equipment_description',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='Hardware_Type',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='MAX_POWER',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='OEM',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='Supported_Cards',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='Techninal_Description',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='Technology_Supported',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='file',
            field=models.FileField(default='abc', upload_to=''),
            preserve_default=False,
        ),
    ]
