# Generated by Django 4.2.6 on 2023-10-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0005_file_column_remove_file_upload_capacity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='file_upload',
        ),
        migrations.DeleteModel(
            name='student_database',
        ),
    ]
